### 1. Получение access и refresh токена
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "email": "hhh@mail.ru",
  "password": "2203"
}





### 2. Проверка работы access токена (GET статей)
GET http://127.0.0.1:8000/api/articles/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjU0MjAzNDksInR5cGUiOiJhY2Nlc3MifQ.qERK4s_FtFXXssftJP76PZ5mEgw_335yHSMDNqqhxd4



### 3. Проверка защиты (POST без токена — должна быть ошибка)
POST http://127.0.0.1:8000/api/articles/
Content-Type: application/json

{
  "title": "Test",
  "text": "Text",
  "category": "IT"
}



### 4. Создание статьи с access токеном
POST http://127.0.0.1:8000/api/articles/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjU0MjAzNDksInR5cGUiOiJhY2Nlc3MifQ.qERK4s_FtFXXssftJP76PZ5mEgw_335yHSMDNqqhxd4

{
  "title": "Статья через REST Client",
  "text": "Это проверка JWT через VS Code",
  "category": "IT"
}



### 5. Обновление access токена через refresh
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjU1MDY1MTgsInR5cGUiOiJyZWZyZXNoIn0.Sj32aSIbPme76ZvKMmn4-TjHfTopyK2_j7jNtOIQ3Xw"
}



### 6. Проверка работы нового access токена
GET http://127.0.0.1:8000/api/articles/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NjU0MjA0NDgsInR5cGUiOiJhY2Nlc3MifQ.K72Br6-USfKcDZdhtaoSF5QHrd2B4AoqONB09GNAMFI
